# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aec68707180e923dd290b042fe26de81ae0c44619f6e61b83efa0885724e15b3129dbf407b92de8f3cd82e679c9b1f2d1e3145c3b5fdb09c80d7306c550091a0

test:
  secret_key_base: 781751e45233d058580a239db1322296fc14ab5d2b2d4cefd32e99917cd04230fead6c7990ff676447cf789f57f88ae5b0bce6835b3975958526edafd22fa9e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
